### PR TITLE
fixed destroy of the plugin

### PR DESCRIPTION
**Pull request by yakimko**

### CODE REVIEW

**Comment by codef0rmer** [comment]
@yakimko What issue does it fix? I believe draggable/droppable directives do not create a child scope so even if the element is removed/destroyed, it's scope will not which makes your PR a bug. Am I missing something here?

**Comment by yakimko** [comment]
It fix memory leak in my application. Because your code didn't call destroy method of draggable plugin.

**Comment by codef0rmer** [comment]
@yakimko: Ah, In that sense your PR looks interesting. Can you create a demo reproducing the issue to understand the problem carefully?

**Comment by yakimko** [comment]
Actually, leaks jquery draggable plugin. I created PR there too. But your code should call destroy method in any case. I will create a demo a bit later.

**Comment by yakimko** [comment]
I've created demos.
 
Current version http://yakimko.github.io/dropdowndemofail
With PRs(jqueryui and angular-dragdrop) http://yakimko.github.io/dropdowndemosuccess

**Comment by codef0rmer** [comment]
@yakimko: Both demos trigger `element.on('$destroy')` or `scope.on('$destroy')` events after I click on return link. I was expecting the fail-demo not to trigger destroy event on the element.

**Comment by yakimko** [comment]
Hmm... You are right. When I tested destroy event in my real application it wasn't triggered. Anyway, could you please accept my PR, just in case?

**Comment by codef0rmer** [comment]
I don't mind but I wanted to reproduce the issue before merging. Would you
mind spending some time to give a thought over why it was failing to
trigger in your app?

**Comment by codef0rmer** [comment]
Closing it as it was not a bug.

**Comment by yakimko** [comment]
Sorry. I'm on vacation and can't check the plugin in my application.

**Comment by yakimko** [comment]
Tested. The plugin is OK.

**Pull request closed without merging**
